[general]
import = ["~/.config/alacritty/github-dark-dimmed.toml"]
live_config_reload = true

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.8
blur = true

[window.padding]
x = 4
y = 4

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000

